# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            CCNx
description:      "Distillery"
logo:             parcxerox_black_solid.png

email: your-email@domain.com
baseurl: "/CCNx_Distillery" # the subpath of your site, e.g. /blog
url: "http://glenncscott.github.io/CCNx_Distillery/" # the base hostname & protocol for your site
twitter_username: ccnx
github_username:  ccnx

# Build settings
markdown: kramdown
exclude: [ Xcode, src, usr, build, dependencies ]
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
  - title: About
    url: /about
